[package]
name = "ascent_macro_tests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascent = { path = "../ascent", default-features = false }

[dev-dependencies]
tryexpand = "0.9.2"
